name: dogs_darwin
description: Darwin marshal linker for the dogs serialization library.
version: 1.0.1-alpha.1
repository: https://github.com/DarwinFramework/dogs

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  darwin_sdk: ^1.1.0-alpha.2
  darwin_marshal: ^1.1.0-alpha.2
  darwin_http: ^1.1.0-alpha.9
  dogs_core: ^1.0.0
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
