name: dogs_generator
description: Code generator for the dogs serialization library.
version: 5.3.0
repository: https://github.com/DarwinFramework/dogs

environment:
  sdk: '>=2.18.6 <4.0.0'

dependencies:
  build: '>=2.0.0 <3.0.0'
  analyzer: ">=2.0.0 <7.0.0"
  source_gen: '>=1.0.0 <=2.0.0'
  collection: '>=1.15.0 <2.0.0'
  crypto: '>=3.0.0 <4.0.0'
  glob: '>=2.0.0 <3.0.0'
  path: '>=1.8.0 <2.0.0'
  code_builder: '>=4.3.0 <5.0.0'
  dart_style: '>=2.2.4 <3.0.0'

  dogs_core: ^8.3.0
  lyell: ^1.1.0
  lyell_gen: ^1.2.4
  pubspec: ^2.3.0
  recase: ^4.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.1
