name: dogs_generator
description: Code generator for the dogs serialization library.
version: 2.0.0
repository: https://github.com/DarwinFramework/dogs

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  build: '>=2.0.0 <3.0.0'
  analyzer: ">=2.0.0 <6.0.0"
  source_gen: '>=1.0.0 <=2.0.0'
  collection: '>=1.15.0 <2.0.0'
  crypto: '>=3.0.0 <4.0.0'
  glob: '>=2.0.0 <3.0.0'
  path: '>=1.8.0 <2.0.0'
  code_builder: '>=4.3.0 <5.0.0'
  dart_style: '>=2.2.4 <3.0.0'

  dogs_core: ^2.0.0
  lyell: ^0.0.2
  lyell_gen: ^0.1.0
dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.2
