name: dogs_cbor
description: Cbor serializer for the dogs graph serializer
version: 2.0.1
repository: https://github.com/DarwinFramework/dogs

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  cbor: ^5.1.2
  dogs_core: ^2.1.0
dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.2
