name: dogs_core
description: a universal serialization library using code generation to reduce boilerplate massively.
version: 3.0.0
repository: https://github.com/DarwinFramework/dogs

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  conduit_open_api: ^4.2.2
  aqueduct_isolates: ^1.0.1
  collection: ^1.17.1
  lyell: ^0.0.2
  meta: ^1.9.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.2
